### ISSUE TITLE
500 on entity search page -- undefined method `couple_path'  

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#1268]
```
INFO -- : Completed 500 Internal Server Error in 53ms (ActiveRecord: 1.1ms | Allocations: 16725)
FATAL -- :
ActionView::Template::Error (undefined method `couple_path' for #<#<Class:0x000055bff859f1b0>:0x000055bff7fdf720>):
    59:     <%= paginate @entities %>
    60:     <% @entities.each do |entity| %>
    61:       <div class="search-result-wrapper entity-search-result">
    62:         <span class="search-result-link"><%= entity_link(entity) %></span> &nbsp;<em><%= highlight((entity.blurb or ""), params[:q]) %></em><br>
    63:         <span class="entity-search-result-summary"><%= highlight(truncate((entity.summary or ""), length: 70), params[:q]) %></span>
    64:       </div>
    65:     <% end %>

app/helpers/entities_helper.rb:33:in `block (3 levels) in <module:EntitiesHelper>'
app/helpers/application_helper.rb:156:in `entity_link'
app/views/search/basic.html.erb:62
app/views/search/basic.html.erb:60
app/controllers/search_controller.rb:29:in `block (2 levels) in basic'
app/controllers/search_controller.rb:28:in `basic'
```

**Comment by robjlucas** [comment]
This will be related to #1262 presumably, the point being that we have inconsistent data/logic when it comes to couples as an entity type. They need to either be properly handled like organisations and people, or entirely removed/migrated.
