### ISSUE TITLE
Amount is nil on profile page

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#189]
```
Processing by EntitiesController#show as HTML
Parameters: {"id"=>"52680"}
INFO -- : Completed 500 Internal Server Error in 102ms (ActiveRecord: 34.4ms)
FATAL -- : 
ActionView::Template::Error (undefined method `amount' for nil:NilClass):
    19:             <% if params[:relationships] == nil %>
    20: 
    21: 		<% cache ['relationship_page', @entity.alt_cache_key] do  %>
    22: 		    <% @links = SortedLinks.new(@entity) %>
    23:                     <% section_order(@entity).each do |section| %>
    24: 			<% links_group = @links.send(section) %>
    25: 			<%= section_heading(links_group) %>
  app/utility/links_group.rb:28:in `block in order'
  app/utility/links_group.rb:28:in `sort'
  app/utility/links_group.rb:28:in `order'
  app/utility/links_group.rb:10:in `initialize'
  app/utility/sorted_links.rb:159:in `new'
  app/utility/sorted_links.rb:159:in `create_donation_subgroups'
  app/utility/sorted_links.rb:107:in `create_subgroups'
  app/utility/sorted_links.rb:65:in `initialize'
  app/views/entities/show.html.erb:22:in `new'
  app/views/entities/show.html.erb:22:in `block in _app_views_entities_show_html_erb__3126845384708572713_64123680'
  app/views/entities/show.html.erb:21:in `_app_views_entities_show_html_erb__3126845384708572713_64123680'

```

**Comment by aepyornis** [comment]
same error as #195
