### ISSUE TITLE
relationship datatable fails to load for democratic sentorial campaign committee

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#369]
Fatal error caused for this request: https://littlesis.org/org/28856-Democratic_Senatorial_Campaign_Committee/datatable

error:
```
INFO -- :   Rendered entities/datatable.html.erb within layouts/application (14753.9ms)
INFO -- : Completed 500 Internal Server Error in 14758ms (ActiveRecord: 2585.3ms)
FATAL -- : ActionView::Template::Error (undefined method `types' for nil:NilClass):
    4: <h3 class="section">Relationships</h3>
    5: 
    6: <% cache( [@entity.alt_cache_key, 'relationships_datatable'], expires_in: 1.day) do %>
    7:   <%= render partial: 'relationships/datatable', locals: { table: RelationshipsDatatable.new(@entity) } %>
    8: <% end %>
  app/utility/relationships_datatable.rb:47:in `block in initialize'
  app/utility/relationships_datatable.rb:42:in `initialize'
  app/views/entities/datatable.html.erb:7:in `new'
  app/views/entities/datatable.html.erb:7:in `block in _app_views_entities_datatable_html_erb__3682902087045859490_70151863748640'
  app/views/entities/datatable.html.erb:6:in `_app_views_entities_datatable_html_erb__3682902087045859490_70151863748640'

```

**Comment by aepyornis** [comment]
this is the result of a relationships that should have been removed but was not.

```
Relationship.find(401153).soft_delete
```

should solve the problem
