### ISSUE TITLE
can't view deletion request review pages after they have been approved

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#467]
Error:

```
INFO -- : Started GET "/deletion_requests/6/review"                                                     
INFO -- : Processing by DeletionRequestsController#review as HTML
 INFO -- :   Parameters: {"id"=>"6"}
 INFO -- : Completed 400 Bad Request in 10ms (ActiveRecord: 3.4ms)                                                                                      
FATAL -- :
FATAL -- : ActionController::ParameterMissing (param is missing or the value is empty: entity_id):                                                      
FATAL -- :
FATAL -- : app/controllers/deletion_requests_controller.rb:35:in `set_entity'                                                                           
INFO -- : Started GET "/deletion_requests/1/review" for                                                  
INFO -- : Processing by DeletionRequestsController#review as HTML                                                                                      
INFO -- :   Parameters: {"id"=>"1"}
INFO -- : Completed 400 Bad Request in 11ms (ActiveRecord: 3.7ms)                                                                                      
FATAL -- :
FATAL -- : ActionController::ParameterMissing (param is missing or the value is empty: entity_id):                                                      
FATAL -- :
ATAL -- : app/controllers/deletion_requests_controller.rb:35:in `set_entity' 
```

One shouldn't be be able to access that page since the request is taken care of, but it should show a message or redirect.

**Comment by lovemedicine** [comment]
This appears to have been fixed!
