### ISSUE TITLE
NoMethodError when bulk adding relationships

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#594]
```
INFO -- : Completed 500 Internal Server Error in 5ms (ActiveRecord: 1.1ms)
FATAL -- :   NoMethodError (undefined method `length' for #<ActionController::Parameters:0x00007f9fa15fdf78>):
FATAL -- :   
FATAL -- : app/controllers/application_controller.rb:69:in `block_unless_bulker'
app/controllers/relationships_controller.rb:88:in `bulk_add!'
```

**Comment by aepyornis** [comment]
solved by d6a048064bff98574ca62200e4da44ded19d4f81 and 5ca91e36eaa5920057fbb8ea72bed23f2a5537b5
