### ISSUE TITLE
chat auth error

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#835]
```
Completed 500 Internal Server Error in 59ms (ActiveRecord: 1.1ms)
Errno::ECONNREFUSED (Failed to open TCP connection to x.x.x.x:3000 (Connection refused - connect(2) for "x.x.x.x" port 3000)):
 app/utility/chat.rb:37:in `admin_login'
app/utility/chat.rb:64:in `api_request'
app/utility/chat.rb:59:in `login_token'
app/controllers/chat_controller.rb:57:in `render_chat_json'
app/controllers/chat_controller.rb:26:in `chat_auth'
```

**Comment by aepyornis** [comment]
fixed!
