### ISSUE TITLE
validation error while soft_deleting an entity

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#908]
``` 
Started DELETE "/entities/124224-Vivendi" 
 Processing by EntitiesController#destroy as HTML
   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "commit"=>"remove", "id"=>"124224-Vivendi"}
Completed 422 Unprocessable Entity in 8ms (ActiveRecord: 3.6ms)
FATAL ActiveRecord::RecordInvalid (Validation failed: Name The name is only one word. Valid names are at least two words):
pp/models/concerns/soft_delete.rb:25:in `block (3 levels) in soft_delete'
app/models/concerns/soft_delete.rb:24:in `block (2 levels) in soft_delete'
app/models/concerns/soft_delete.rb:57:in `set_paper_trail_event'
app/models/concerns/soft_delete.rb:23:in `block in soft_delete'
app/models/concerns/soft_delete.rb:22:in `soft_delete'
app/controllers/entities_controller.rb:119:in `destroy'
```

**Comment by lovemedicine** [comment]
Can't reproduce this bug, it was probably either fixed or the entity had weird data
