### ISSUE TITLE
Error merging with duplicate crd numbers

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#991]
` /merge?mode=execute&source=349351&dest=183749 `

error:

```
FATAL ActiveRecord::RecordNotUnique (Mysql2::Error: Duplicate entry '4479315' for key 'index_business_person_on_crd_number': UPDATE `business_person` SET `crd_number` = 4479315 WHERE `business_person`.`id` = 49539):
app/models/concerns/entity_extensions.rb:233:in `merge_extension'
app/utility/entity_merger.rb:116:in `merge!'
app/utility/entity_merger.rb:25:in `block (2 levels) in merge!'
app/utility/entity_merger.rb:25:in `each'
app/utility/entity_merger.rb:25:in `block in merge!'
app/utility/entity_merger.rb:24:in `merge!'
app/models/entity.rb:654:in `merge_with'
app/controllers/merge_controller.rb:31:in `merge!'
```

**Comment by lovemedicine** [comment]
Investigate whether moving crd field to external link fixed this issue.
